# Form implementation generated from reading ui file 'second.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(693, 482)
        self.scrollArea = QtWidgets.QScrollArea(parent=Form)
        self.scrollArea.setGeometry(QtCore.QRect(0, 10, 681, 361))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 679, 359))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.tableView = QtWidgets.QTableView(parent=self.scrollAreaWidgetContents)
        self.tableView.setGeometry(QtCore.QRect(5, 11, 671, 301))
        self.tableView.setObjectName("tableView")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.loadButton = QtWidgets.QPushButton(parent=Form)
        self.loadButton.setGeometry(QtCore.QRect(550, 420, 93, 28))
        self.loadButton.setObjectName("loadButton")
        self.backButton = QtWidgets.QPushButton(parent=Form)
        self.backButton.setGeometry(QtCore.QRect(20, 410, 93, 28))
        self.backButton.setObjectName("backButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.loadButton.setText(_translate("Form", "PushButton"))
        self.backButton.setText(_translate("Form", "назад"))
